[package]
name = "legato"
version = "1.0.0"
authors = []

[addresses]
legato_addr='b586d128941c1167ee7947fbec8949057f489661f52f08580d90b9831d8c7a9d'
aptos_framework = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
